# create all meeting roles
Role.find_or_create_by_name("Toastmaster")
Role.find_or_create_by_name("First Speaker")
Role.find_or_create_by_name("Second Speaker")
Role.find_or_create_by_name("Third Speaker")
Role.find_or_create_by_name("Topicsmaster")
Role.find_or_create_by_name("General Evaluator")
Role.find_or_create_by_name("First Evaluator")
Role.find_or_create_by_name("Second Evaluator")
Role.find_or_create_by_name("Third Evaluator")
Role.find_or_create_by_name("Pledge")
Role.find_or_create_by_name("Thought of the Day")
Role.find_or_create_by_name("Timer")
Role.find_or_create_by_name("Grammarian")
Role.find_or_create_by_name("Ah-Counter")
Role.find_or_create_by_name("Listener")
Role.find_or_create_by_name("Attendee")
